import Link from "next/link";
import { ArrowDown, ArrowRight, Clock3, MapPin, QrCode } from "lucide-react";
import { CategoryTile } from "@/components/CategoryTile";
import { getCategories, getProducts } from "@/lib/cms";
import { ProductList } from "@/components/ProductCard";

export default async function Home() {
  const [categories, products] = await Promise.all([getCategories(), getProducts()]);
  const drinks = products.filter((product) => product.category === "getraenke");
  const coffeeAndTea = drinks.filter((product) => ["kaffeeklassiker", "teesorten"].includes(product.slug));
  const otherCategories = categories.filter((category) => category.slug !== "getraenke");
  return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">Dein digitales Café-Menü</p><h1>Kaffee zuerst,<br /><em>Herbst dazu.</em></h1><p className="hero-lead">QR-Code scannen und direkt zu Kaffee, Tee und unseren Getränken springen. Backwaren und Süsswaren findest du gleich darunter.</p><Link href="/kategorie/getraenke" className="primary-button">Getränke öffnen <ArrowRight size={17} /></Link></div><div className="hero-art"><div className="sun"></div><div className="hero-emoji">☕</div><span className="art-note note-one">caffè jonasch</span><span className="art-note note-two">mobile first</span></div></section><section className="market-info" aria-label="Informationen zum Herbstmarkt"><div className="market-info-item"><MapPin size={20} /><div><p className="eyebrow">Wo du uns findest</p><strong>Herbstmarkt auf dem Petersplatz</strong><span>Mitten in Basel · direkt am Marktstand</span></div></div><div className="market-info-item"><Clock3 size={20} /><div><p className="eyebrow">Wann wir da sind</p><strong>Täglich von 11 bis 20 Uhr</strong><span>Wir freuen uns auf deinen Besuch</span></div></div><Link href="/kategorie/getraenke" className="market-info-qr"><QrCode size={22} /><span>Direkt zu Kaffee &amp; Tee<br /><b>QR-Code scannen</b></span></Link></section><section className="coffee-first section"><div className="section-heading compact"><div><p className="eyebrow">Für Kaffeegäste</p><h2>Kaffee &amp; Tee<br /><em>sofort bereit.</em></h2></div><Link href="/kategorie/getraenke" className="text-link">Alle Getränke <ArrowRight size={15} /></Link></div><ProductList products={coffeeAndTea} /></section><section id="menue" className="section category-section"><div className="section-heading"><div><p className="eyebrow">Weitere Auswahl</p><h2>Etwas Süsses,<br /><em>etwas Gutes.</em></h2></div><div className="open-note"><QrCode size={16} /><span>Getränke zuerst<br /><b>ohne App</b></span></div></div><div className="category-grid">{otherCategories.map((category) => <CategoryTile key={category.slug} category={category} />)}</div></section><section className="section featured"><div className="section-heading compact"><div><p className="eyebrow">Das vollständige Getränkeangebot</p><h2>Auch zum Anstossen</h2></div><span className="season-stamp">MENÜ<br /><b>2026</b></span></div><ProductList products={drinks.slice(2)} /></section></main>;
}
